apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-ui
  template:
    metadata:
      labels:
        app: micro-ui
    spec:
      containers:
      - name: micro-ui
        image: nginx:latest
        ports:
        - containerPort: 80
